/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgtmtr;

import claseConectar.conectar;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZuluCorp
 */
public class bcliente2 extends javax.swing.JInternalFrame {
    DefaultTableModel modelo;
    ValidarCaracteres validarLetras = new ValidarCaracteres();
    /**
     * Creates new form bv
     */
    public bcliente2() {
        initComponents();
        setTitle("Selección de cliente");
        this.setLocation(280,200);
        mostrarvehiculos("");
        anchocolumnas();
    }
void mostrarvehiculos(String valor)
    {
        String[]titulos={"RUT","Nombres","Apellidos","Fono","Dirección","E-mail"} ;  
        String []Registros= new String[6];
        modelo=new DefaultTableModel(null,titulos);
        String Sql="SELECT * FROM clientes WHERE CONCAT(RUT,Nombres,Apellidos,Contacto) LIKE '%"+valor+"%'";
       
        try {
             Statement st = cn.createStatement();
             ResultSet rs = st.executeQuery(Sql);
             while(rs.next())
             {
                 Registros[0]=rs.getString("RUT");  
                 Registros[1]=rs.getString("Nombres");  
                 Registros[2]=rs.getString("Apellidos");  
                 Registros[3]=rs.getString("Contacto");  
                 Registros[4]=rs.getString("Direccion");  
                 Registros[5]=rs.getString("Correo"); 
                 modelo.addRow(Registros);
             } 
             tbcliente.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(bv.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void anchocolumnas() {
        tbcliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        tbcliente.getColumnModel().getColumn(0).setWidth(100);
        tbcliente.getColumnModel().getColumn(0).setMaxWidth(100);
        tbcliente.getColumnModel().getColumn(0).setMinWidth(100);
        
        tbcliente.getColumnModel().getColumn(1).setWidth(100);
        tbcliente.getColumnModel().getColumn(1).setMaxWidth(100);
        tbcliente.getColumnModel().getColumn(1).setMinWidth(100);

        tbcliente.getColumnModel().getColumn(2).setWidth(100);
        tbcliente.getColumnModel().getColumn(2).setMaxWidth(100);
        tbcliente.getColumnModel().getColumn(2).setMinWidth(100);

        tbcliente.getColumnModel().getColumn(3).setWidth(120);
        tbcliente.getColumnModel().getColumn(3).setMaxWidth(120);
        tbcliente.getColumnModel().getColumn(3).setMinWidth(120);

        tbcliente.getColumnModel().getColumn(4).setWidth(90);
        tbcliente.getColumnModel().getColumn(4).setMaxWidth(90);
        tbcliente.getColumnModel().getColumn(4).setMinWidth(90);

        tbcliente.getColumnModel().getColumn(5).setWidth(200);
        tbcliente.getColumnModel().getColumn(5).setMaxWidth(200);
        tbcliente.getColumnModel().getColumn(5).setMinWidth(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        jsp = new javax.swing.JScrollPane();
        tbcliente = new javax.swing.JTable();
        btnenviar = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione al cliente comprador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel1.setText("RUT");

        txtrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrutKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutKeyTyped(evt);
            }
        });

        //Deshabilitar edicion de tabla
        tbcliente = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        //cambiar color de fila
        tbcliente.setSelectionBackground(Color.LIGHT_GRAY);
        tbcliente.setSelectionForeground(Color.blue);
        tbcliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbcliente.getTableHeader().setResizingAllowed(false);
        tbcliente.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tbcliente);

        btnenviar.setText("Enviar");
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnenviar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnenviar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyReleased
         mostrarvehiculos(txtrut.getText());
    }//GEN-LAST:event_txtrutKeyReleased

    private void txtrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyTyped
        validarLetras.soloRUT(evt);
        //limite de caracteres
        if (txtrut.getText().length() == 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtrutKeyTyped

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        String rut = "", nom = "", ap = "", cont = "", dire = "", mail = "";
        int fila = tbcliente.getSelectedRow();
        try {
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ningun dato");

            } else {
                rut = (String) tbcliente.getValueAt(fila, 0);
                nom = (String) tbcliente.getValueAt(fila, 1);
                ap = (String) tbcliente.getValueAt(fila, 2);
                cont = (String) tbcliente.getValueAt(fila, 3);
                dire = (String) tbcliente.getValueAt(fila, 4);
                mail = (String) tbcliente.getValueAt(fila, 5);

                ComprobanteVta.txtrut.setText(rut);
                ComprobanteVta.txtnombrecomp.setText(nom+" "+ap);
                ComprobanteVta.txtfono.setText(cont);
                ComprobanteVta.txtdireccion.setText(dire);
                ComprobanteVta.txtemail.setText(mail);
                this.dispose();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnenviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTable tbcliente;
    private javax.swing.JTextField txtrut;
    // End of variables declaration//GEN-END:variables
    conectar cc= new conectar();
    Connection cn = cc.conexion();
}
