/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgtmtr;

import static claseConectar.ConexionConBaseDatos.conexion;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZuluCorp
 */
public class bcliente2 extends javax.swing.JInternalFrame {

    DefaultTableModel modelo;
    ValidarCaracteres validarLetras = new ValidarCaracteres();

    /**
     * Creates new form bv
     */
    public bcliente2() {
        initComponents();
        setTitle("Selección de cliente");
        this.setLocation(280, 200);
        mostrarvehiculos("");
        anchocolumnas();
    }

    void mostrarvehiculos(String valor) {
        String[] titulos = {"RUT", "Nombres", "Apellidos", "Fono", "Dirección", "E-mail"};
        String[] Registros = new String[6];
        modelo = new DefaultTableModel(null, titulos);
        String Sql = "SELECT * FROM clientes WHERE CONCAT(RUT,Nombres,Apellidos,Contacto) LIKE '%" + valor + "%'";

        try {
            conexion = claseConectar.ConexionConBaseDatos.getConexion();
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(Sql);
            while (rs.next()) {
                Registros[0] = rs.getString("RUT");
                Registros[1] = rs.getString("Nombres");
                Registros[2] = rs.getString("Apellidos");
                Registros[3] = rs.getString("Contacto");
                Registros[4] = rs.getString("Direccion");
                Registros[5] = rs.getString("Correo");
                modelo.addRow(Registros);
            }
            tbcliente.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(bv.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            claseConectar.ConexionConBaseDatos.metodoCerrarConexiones(conexion);
        }
    }

    void anchocolumnas() {
        tbcliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        tbcliente.getColumnModel().getColumn(0).setWidth(100);
        tbcliente.getColumnModel().getColumn(0).setMaxWidth(100);
        tbcliente.getColumnModel().getColumn(0).setMinWidth(100);

        tbcliente.getColumnModel().getColumn(1).setWidth(100);
        tbcliente.getColumnModel().getColumn(1).setMaxWidth(100);
        tbcliente.getColumnModel().getColumn(1).setMinWidth(100);

        tbcliente.getColumnModel().getColumn(2).setWidth(100);
        tbcliente.getColumnModel().getColumn(2).setMaxWidth(100);
        tbcliente.getColumnModel().getColumn(2).setMinWidth(100);

        tbcliente.getColumnModel().getColumn(3).setWidth(120);
        tbcliente.getColumnModel().getColumn(3).setMaxWidth(120);
        tbcliente.getColumnModel().getColumn(3).setMinWidth(120);

        tbcliente.getColumnModel().getColumn(4).setWidth(90);
        tbcliente.getColumnModel().getColumn(4).setMaxWidth(90);
        tbcliente.getColumnModel().getColumn(4).setMinWidth(90);

        tbcliente.getColumnModel().getColumn(5).setWidth(200);
        tbcliente.getColumnModel().getColumn(5).setMaxWidth(200);
        tbcliente.getColumnModel().getColumn(5).setMinWidth(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new elaprendiz.gui.panel.PanelImage();
        panelTranslucido1 = new elaprendiz.gui.panel.PanelTranslucido();
        jLabel1 = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        jsp = new javax.swing.JScrollPane();
        tbcliente = new javax.swing.JTable();

        setClosable(true);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoazulceleste.jpg"))); // NOI18N

        panelTranslucido1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione al cliente comprador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RUT");

        txtrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutActionPerformed(evt);
            }
        });
        txtrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrutKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutKeyTyped(evt);
            }
        });

        //Deshabilitar edicion de tabla
        tbcliente = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        //cambiar color de fila
        tbcliente.setSelectionBackground(Color.LIGHT_GRAY);
        tbcliente.setSelectionForeground(Color.blue);
        tbcliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbcliente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbcliente.getTableHeader().setResizingAllowed(false);
        tbcliente.getTableHeader().setReorderingAllowed(false);
        tbcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbclienteMousePressed(evt);
            }
        });
        jsp.setViewportView(tbcliente);

        javax.swing.GroupLayout panelTranslucido1Layout = new javax.swing.GroupLayout(panelTranslucido1);
        panelTranslucido1.setLayout(panelTranslucido1Layout);
        panelTranslucido1Layout.setHorizontalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTranslucido1Layout.setVerticalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyReleased
        mostrarvehiculos(txtrut.getText());
    }//GEN-LAST:event_txtrutKeyReleased

    private void txtrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyTyped
        validarLetras.soloRUT(evt);
        //limite de caracteres
        if (txtrut.getText().length() == 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtrutKeyTyped

    private void tbclienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbclienteMousePressed
        String rut = "", nom = "", ap = "", cont = "", dire = "", mail = "";
        int fila = tbcliente.getSelectedRow();
        try {
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ningun dato");

            } else {
                rut = (String) tbcliente.getValueAt(fila, 0);
                nom = (String) tbcliente.getValueAt(fila, 1);
                ap = (String) tbcliente.getValueAt(fila, 2);
                cont = (String) tbcliente.getValueAt(fila, 3);
                dire = (String) tbcliente.getValueAt(fila, 4);
                mail = (String) tbcliente.getValueAt(fila, 5);

                ComprobanteVta.txtrut.setText(rut);
                ComprobanteVta.txtnombrecomp.setText(nom + " " + ap);
                ComprobanteVta.txtfono.setText(cont);
                ComprobanteVta.txtdireccion.setText(dire);
                ComprobanteVta.txtemail.setText(mail);
                this.dispose();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tbclienteMousePressed

    private void txtrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jsp;
    private elaprendiz.gui.panel.PanelImage panelImage1;
    private elaprendiz.gui.panel.PanelTranslucido panelTranslucido1;
    private javax.swing.JTable tbcliente;
    private javax.swing.JTextField txtrut;
    // End of variables declaration//GEN-END:variables
}
