/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgtmtr;

/**
 *
 * @author ZuluCorp
 */
public class detallediagnostico extends javax.swing.JInternalFrame {

    /**
     * Creates new form detallediagnostico
     */
    public detallediagnostico() {
        initComponents();
    }

    /**
         * Le da formato a un rut, concatenándole puntos y guión.
         *
         * @param rut Rut a formatear.
         * @return Un nuevo String, con el rut formateado.
         */
        static public String formatear(String rut) {
            int cont = 0;
            String format;
            if (rut.length() == 0) {
                return "";
            } else {
                rut = rut.replace(".", "");
                rut = rut.replace("-", "");
                format = "-" + rut.substring(rut.length() - 1);
                for (int i = rut.length() - 2; i >= 0; i--) {
                    format = rut.substring(i, i + 1) + format;
                    cont++;
                    if (cont == 3 && i != 0) {
                        format = "." + format;
                        cont = 0;
                    }
                }
                return format;
            }
        }

        /**
         * Valida un rut de acuerdo a su dígito verificador.
         *
         * @param rut Rut a validar
         * @return true si el rut es válido, false en cualquier otro caso.
         */
        static public boolean validar(String rut) {
            int suma = 0;
            String dvR, dvT;
            int[] serie = {2, 3, 4, 5, 6, 7};
            rut = rut.replace(".", "");
            rut = rut.replace("-", "");
            dvR = rut.substring(rut.length() - 1);
            for (int i = rut.length() - 2; i >= 0; i--) {
                suma += Integer.valueOf(rut.substring(i, i + 1))
                        * serie[(rut.length() - 2 - i) % 6];
            }
            dvT = String.valueOf(11 - suma % 11);
            if (dvT.compareToIgnoreCase("10") == 0) {
                dvT = "K";
            }

            if (dvT.compareToIgnoreCase(dvR) == 0) {
                return true;
            } else {
                return false;
            }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setClosable(true);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        jFormattedTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        formatear(jTextField1.getText());
        if (validar(jTextField1.getText())) {
            System.out.println("Rut Válido");
        } else {
            System.out.println("Rut Inválido");
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jFormattedTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField1FocusLost

        
    }//GEN-LAST:event_jFormattedTextField1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
