/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgtmtr;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ZuluCorp
 */
public class Login extends javax.swing.JDialog {

    int intentos = 4;
    //Propiedad para indicar a la ventana principal el tipo de usuario
    static int tipoUsuario;
    //Propiedad para indicar a la ventana principal el nombre de Usuario
    static String nomUsuario;
    static String contraseña;
    static String Nombres;
    static String Apellidos;
    static String Cargo;

    ValidarCaracteres validarLetras = new ValidarCaracteres();

    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //centrar la pantalla
        setLocationRelativeTo(null);
        setTitle("Validación de Usuarios del Sistema");
        txtuser.requestFocus();
    }

    public void keyTyped(KeyEvent ke) {
        char c = ke.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            ke.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new elaprendiz.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btiniciar = new javax.swing.JButton();
        panelImage2 = new elaprendiz.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoazulceleste.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");

        txtuser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuserKeyTyped(evt);
            }
        });

        txtpass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpassKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");

        btiniciar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login.png"))); // NOI18N
        btiniciar.setText("Iniciar Sesión");
        btiniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btiniciar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btiniciar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btiniciarActionPerformed(evt);
            }
        });
        btiniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btiniciarKeyPressed(evt);
            }
        });

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/llavelogin.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                        .addGap(0, 88, Short.MAX_VALUE)
                        .addComponent(btiniciar))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpass)
                            .addComponent(txtuser))))
                .addGap(32, 32, 32))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(txtpass, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btiniciar)
                .addGap(25, 25, 25))
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btiniciarActionPerformed
        Validar();
    }//GEN-LAST:event_btiniciarActionPerformed

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Validar();
        } else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            btiniciar.setFocusable(true);
        }
        validarVacios();
        //Impedir teclear algunos caraceres para no inyectar query
        txtpass.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter == 32))
                        || (caracter == '@')
                        || (caracter == ';')
                        || (caracter == '|')
                        || (caracter == '&')
                        || (caracter == 39)
                        || (caracter == 13)
                        || (caracter == '=')
                        || (caracter == '*')) {
                    e.consume();
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        });
    }//GEN-LAST:event_txtpassKeyPressed

    private void txtuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyPressed
        validarVacios();
        //Impedir teclear algunos caraceres para no inyectar query
        txtuser.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (((caracter == 32))
                        || (caracter == '@')
                        || (caracter == ';')
                        || (caracter == '|')
                        || (caracter == '&')
                        || (caracter == 39)
                        || (caracter == 13)
                        || (caracter == '=')
                        || (caracter == '*')) {
                    e.consume();
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        });
    }//GEN-LAST:event_txtuserKeyPressed

    private void txtuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyTyped
        validarLetras.LoginUser(evt);
        if (txtuser.getText().length() == 15) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtuserKeyTyped

    private void txtpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyTyped
        validarLetras.soloLetrasyNumeros(evt);
        //limite de caracteres
        if (txtpass.getText().length() == 15) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtpassKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void btiniciarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btiniciarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Validar();
        }
    }//GEN-LAST:event_btiniciarKeyPressed

    private void validarVacios() {
        if (String.valueOf(txtuser.getText()).compareTo("") == 0
                || String.valueOf(txtpass.getText()).compareTo("") == 0) {
            btiniciar.setEnabled(false);
            return;
        } else {
            btiniciar.setEnabled(true);
            return;
        }
    }

    private void Validar() {
        // Verificar Ingreso
        try {
           //Cargar driver de conexión
            Class.forName("com.mysql.jdbc.Driver");
            //Crear conexión
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/techorojo", "root", "");
            //Crear consulta
            Statement st = con.createStatement();
            String sql = "SELECT u.IDTB, u.ID, u.Nombres, u.Apellidos, tu.TipoUser, u.TipoUsuario, u.Usuario, u.Password FROM usuarios u, tipousuario tu WHERE u.TipoUsuario=tu.IDTU && Usuario='" + txtuser.getText() + "' and Password='" + txtpass.getText() + "'";
            //Ejecutar la consulta
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                //existe

                //tfusuario.setText(rs.getObject("Usuario").toString());
                //tfpassword.setText(rs.getObject("Password").toString());
                /**
                 * *****************************************************
                 */
                //asumo que la tabla login tiene un campo tipo
                //para poder saber si le debo o no mostrar el menu
                //Usuario de la ventana Principal
                //Para lograrlo me valgo de una variable compartida dentro
                //de la clase Validacion. El nombre de la variable
                //es tipoUsuario > Continua en vPrincipal->formWindowOpened
                ClassUtils.USUARIO_CONECTADO = rs.getInt("IDTB");
                Login.nomUsuario = rs.getString("Usuario");
                Login.tipoUsuario = rs.getInt("TipoUsuario");
                Login.Nombres = rs.getString("Nombres");
                Login.Apellidos = rs.getString("Apellidos");
                Login.Cargo = rs.getString("TipoUser");
                JOptionPane.showMessageDialog(null, "Bienvenido al sistema: " + Login.Nombres + " " + Login.Apellidos + ".");
                dispose();
            } else {
                this.intentos--;
                //no existe
                JOptionPane.showMessageDialog(this, "Usuario y/o contraseña no válidos, le quedan " + this.intentos + " intentos");
                if (this.intentos == 0) {
                    System.exit(0);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error " + e.getMessage().toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btiniciar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private elaprendiz.gui.panel.PanelImage panelImage1;
    private elaprendiz.gui.panel.PanelImage panelImage2;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
