/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgtmtr;

import static claseConectar.ConexionConBaseDatos.conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ZuluCorp
 */
public class Principal extends javax.swing.JFrame {

    //calcular fecha
    public static String fechaActual() {
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-YYYY");
        return formatoFecha.format(fecha);
    }

    /**
     * Creates new form Principal
     */
    javax.swing.ImageIcon iconoConectado = new javax.swing.ImageIcon(getClass().getResource("/Imagenes/status_online.png"));
    javax.swing.ImageIcon iconoDesconectado = new javax.swing.ImageIcon(getClass().getResource("/Imagenes/status_offline.png"));

    public Principal() {
        super("Sistema de Gestión de Taller Mecánico");
        //Abrir ventana de validacion de usuarios
        new Login(this, true).setVisible(true);
        initComponents();
        clockDigital1.show();
        lbfecha.setText(fechaActual());
        //centrar la pantalla
        //setLocationRelativeTo(null);
        //fondos
        panelImagen.setVisible(true);
        //fondo1.setVisible(false);
        //this.setSize(1000, 768);
        //maximizar pantalla por defecto al abrir el form
        this.setExtendedState(MAXIMIZED_BOTH);
        //this.setLocation(600,150);
        //icono
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/business_logo.png"));
        setIconImage(icon);
        //Mostramos el nombre de Usuario
        lblusuario.setText("Usuario Conectado: "+Login.Nombres + " " + Login.Apellidos);
        lbltipo.setText("Tipo de Usuario: " + Login.Cargo);
        this.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {

            }

            @Override
            public void windowClosing(WindowEvent e) {

                int rpt = JOptionPane.showConfirmDialog(null, "¿Seguro que desea salir del programa?", "¡Advertencia!", JOptionPane.YES_NO_OPTION);
                if (rpt == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }

            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {

            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {

            }

            @Override
            public void windowDeactivated(WindowEvent e) {

            }

        });
        
        //lbnombres.setText("Nombres: " + Login.Nombres);
        // lbapellidos.setText("Apellidos: " + Login.Apellidos);
        /*btnusuarios.setOpaque(false);
         .setContentAreaFilled(false);
         btnusuarios.setBorderPainted(false);*/
    }
       //llamado jInternalframes
    UsuariosSistema us = new UsuariosSistema(); //crear el nuevo formulario
    Insumos in = new Insumos(); //crear el nuevo formulario
    ConsultaComprobantes ccvta = new ConsultaComprobantes(); //crear el nuevo formulario
    UsuariosSistema us2 = new UsuariosSistema(); //crear el nuevo formulario
    ClientesSistema cs = new ClientesSistema(); //crear el nuevo formulario
    MarcaVehiculo mv = new MarcaVehiculo(); //crear el nuevo formulario
    vehiculos v = new vehiculos(); //crear el nuevo formulario
    Desperfectos d = new Desperfectos(); //crear el nuevo formulario
    diagnostico diag = new diagnostico(); //crear el nuevo formulario
    ComprobanteVta cvta = new ComprobanteVta(); //crear el nuevo formulario

    private void deshabilitarmenu() {
        this.mnireportes.setVisible(false);
        this.mnicambiarpass.setVisible(false);
        this.mnicerrarsesion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jdpescritorio = new javax.swing.JDesktopPane();
        panelImagen = new elaprendiz.gui.panel.PanelImage();
        panelCurves1 = new elaprendiz.gui.panel.PanelCurves();
        lblimg = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lbfecha = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        clockDigital1 = new elaprendiz.gui.varios.ClockDigital();
        paneldueño = new elaprendiz.gui.panel.PanelTranslucido();
        btnusuarios = new javax.swing.JButton();
        btninsumos = new javax.swing.JButton();
        btnbd = new javax.swing.JButton();
        btncvi = new javax.swing.JButton();
        lbltipo = new javax.swing.JLabel();
        paneljefe = new elaprendiz.gui.panel.PanelTranslucido();
        btnclientes = new javax.swing.JButton();
        btnmarcas = new javax.swing.JButton();
        btnvehiculos = new javax.swing.JButton();
        btndesperfectos = new javax.swing.JButton();
        btnusuarios1 = new javax.swing.JButton();
        panelmecanico = new elaprendiz.gui.panel.PanelTranslucido();
        btndiagnostico = new javax.swing.JButton();
        btnreparaciones = new javax.swing.JButton();
        panelsecretaria = new elaprendiz.gui.panel.PanelTranslucido();
        btnvtains = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnipersonal = new javax.swing.JMenu();
        mnicambiarpass = new javax.swing.JMenuItem();
        mnicerrarsesion = new javax.swing.JMenuItem();
        mnireportes = new javax.swing.JMenu();
        mniusers = new javax.swing.JMenuItem();
        mnirepclientes = new javax.swing.JMenuItem();
        mnirepmarcas = new javax.swing.JMenuItem();
        mnirepdesperfectos = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        mniayuda = new javax.swing.JMenu();
        mniacercade = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jdpescritorio.setBackground(new java.awt.Color(25, 153, 153));

        panelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageVentana/audi-rs5-en-carretera-2125_3.jpg"))); // NOI18N

        lblimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/status_online.png"))); // NOI18N

        lblusuario.setBackground(new java.awt.Color(0, 153, 153));
        lblusuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(0, 102, 102));
        lblusuario.setText("Usuario Conectado: ");

        lblfecha.setBackground(new java.awt.Color(0, 153, 153));
        lblfecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(0, 102, 102));
        lblfecha.setText("Fecha:");

        lbfecha.setBackground(new java.awt.Color(0, 153, 153));
        lbfecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbfecha.setForeground(new java.awt.Color(0, 102, 102));
        lbfecha.setText("jLabel1");

        lblhora.setBackground(new java.awt.Color(0, 153, 153));
        lblhora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblhora.setForeground(new java.awt.Color(0, 102, 102));
        lblhora.setText("Hora:");

        clockDigital1.setBackground(new java.awt.Color(0, 153, 153));
        clockDigital1.setForeground(new java.awt.Color(0, 102, 102));
        clockDigital1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btnusuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agente.png"))); // NOI18N
        btnusuarios.setText("Usuarios");
        btnusuarios.setOpaque(false);
        btnusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuariosActionPerformed(evt);
            }
        });

        btninsumos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btninsumos.setText("Insumos");
        btninsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsumosActionPerformed(evt);
            }
        });

        btnbd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/copia-seguridad.png"))); // NOI18N
        btnbd.setText("Base de Datos");
        btnbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbdActionPerformed(evt);
            }
        });

        btncvi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncvi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconopdf.gif"))); // NOI18N
        btncvi.setText("Consulta de Ventas");
        btncvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncviActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneldueñoLayout = new javax.swing.GroupLayout(paneldueño);
        paneldueño.setLayout(paneldueñoLayout);
        paneldueñoLayout.setHorizontalGroup(
            paneldueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldueñoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(paneldueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncvi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btninsumos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        paneldueñoLayout.setVerticalGroup(
            paneldueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldueñoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnusuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btninsumos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncvi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbltipo.setBackground(new java.awt.Color(0, 153, 153));
        lbltipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltipo.setForeground(new java.awt.Color(0, 102, 102));
        lbltipo.setText("Tipo:");

        btnclientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientesG-32x32.png"))); // NOI18N
        btnclientes.setText("Clientes");
        btnclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientesActionPerformed(evt);
            }
        });

        btnmarcas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnmarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico_bmw_0.png"))); // NOI18N
        btnmarcas.setText("Marcas");
        btnmarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarcasActionPerformed(evt);
            }
        });

        btnvehiculos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnvehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/92341_steering_wheel-512.png"))); // NOI18N
        btnvehiculos.setText("Vehículos");
        btnvehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvehiculosActionPerformed(evt);
            }
        });

        btndesperfectos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndesperfectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/multi.png"))); // NOI18N
        btndesperfectos.setText("Desperfectos");
        btndesperfectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndesperfectosActionPerformed(evt);
            }
        });

        btnusuarios1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnusuarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agente.png"))); // NOI18N
        btnusuarios1.setText("Usuarios");
        btnusuarios1.setOpaque(false);
        btnusuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuarios1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneljefeLayout = new javax.swing.GroupLayout(paneljefe);
        paneljefe.setLayout(paneljefeLayout);
        paneljefeLayout.setHorizontalGroup(
            paneljefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneljefeLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(paneljefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnusuarios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndesperfectos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnvehiculos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmarcas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnclientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        paneljefeLayout.setVerticalGroup(
            paneljefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneljefeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnusuarios1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnclientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmarcas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnvehiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndesperfectos)
                .addContainerGap())
        );

        btndiagnostico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndiagnostico.setText("Diagnósticos");
        btndiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiagnosticoActionPerformed(evt);
            }
        });

        btnreparaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreparaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-32-reparacion.png"))); // NOI18N
        btnreparaciones.setText("Reparaciones");
        btnreparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreparacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelmecanicoLayout = new javax.swing.GroupLayout(panelmecanico);
        panelmecanico.setLayout(panelmecanicoLayout);
        panelmecanicoLayout.setHorizontalGroup(
            panelmecanicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmecanicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelmecanicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnreparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        panelmecanicoLayout.setVerticalGroup(
            panelmecanicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmecanicoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btndiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnreparaciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnvtains.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnvtains.setText("Venta de Insumos");
        btnvtains.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvtainsActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Actualización Estado Diagnóstico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/money.png"))); // NOI18N
        jButton2.setText("Pago de Reparaciones");

        javax.swing.GroupLayout panelsecretariaLayout = new javax.swing.GroupLayout(panelsecretaria);
        panelsecretaria.setLayout(panelsecretariaLayout);
        panelsecretariaLayout.setHorizontalGroup(
            panelsecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsecretariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelsecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnvtains, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelsecretariaLayout.createSequentialGroup()
                        .addGroup(panelsecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelsecretariaLayout.setVerticalGroup(
            panelsecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsecretariaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnvtains)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paneldueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paneljefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 313, Short.MAX_VALUE))
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCurves1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblimg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblusuario)
                                .addGap(79, 79, 79)
                                .addComponent(lbltipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblfecha)
                                .addGap(18, 18, 18)
                                .addComponent(lbfecha))
                            .addComponent(panelmecanico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(lblhora)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clockDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addComponent(panelsecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clockDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfecha)
                            .addComponent(lbfecha))
                        .addComponent(lblhora))
                    .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblusuario)
                        .addComponent(lbltipo))
                    .addComponent(lblimg))
                .addGap(18, 18, 18)
                .addComponent(paneldueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneljefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelmecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelsecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jdpescritorioLayout = new javax.swing.GroupLayout(jdpescritorio);
        jdpescritorio.setLayout(jdpescritorioLayout);
        jdpescritorioLayout.setHorizontalGroup(
            jdpescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdpescritorioLayout.setVerticalGroup(
            jdpescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdpescritorio.setLayer(panelImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuBar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        mnipersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder.png"))); // NOI18N
        mnipersonal.setText("Personal");
        mnipersonal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mnipersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnipersonal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnipersonal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mnipersonal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnicambiarpass.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mnicambiarpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/key_2_32x32.png"))); // NOI18N
        mnicambiarpass.setText("Cambiar Contraseña");
        mnicambiarpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnicambiarpassActionPerformed(evt);
            }
        });
        mnipersonal.add(mnicambiarpass);

        mnicerrarsesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mnicerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disconnect.png"))); // NOI18N
        mnicerrarsesion.setText("Cerrar Sesión");
        mnicerrarsesion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnicerrarsesionItemStateChanged(evt);
            }
        });
        mnicerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnicerrarsesionActionPerformed(evt);
            }
        });
        mnipersonal.add(mnicerrarsesion);

        jMenuBar1.add(mnipersonal);

        mnireportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconopdf.gif"))); // NOI18N
        mnireportes.setText("Reportes");
        mnireportes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mnireportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnireportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnireportes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mnireportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mniusers.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniusers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/group_key.png"))); // NOI18N
        mniusers.setText("Usuarios");
        mniusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniusersActionPerformed(evt);
            }
        });
        mnireportes.add(mniusers);

        mnirepclientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mnirepclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientesG-32x32.png"))); // NOI18N
        mnirepclientes.setText("Clientes");
        mnirepclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnirepclientesActionPerformed(evt);
            }
        });
        mnireportes.add(mnirepclientes);

        mnirepmarcas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mnirepmarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico_bmw_0.png"))); // NOI18N
        mnirepmarcas.setText("Marcas");
        mnirepmarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnirepmarcasActionPerformed(evt);
            }
        });
        mnireportes.add(mnirepmarcas);

        mnirepdesperfectos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mnirepdesperfectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/multi.png"))); // NOI18N
        mnirepdesperfectos.setText("Desperfectos");
        mnirepdesperfectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnirepdesperfectosActionPerformed(evt);
            }
        });
        mnireportes.add(mnirepdesperfectos);

        jMenuItem3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coins.png"))); // NOI18N
        jMenuItem3.setText("Diagnósticos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnireportes.add(jMenuItem3);

        jMenuItem6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/history_button.png"))); // NOI18N
        jMenuItem6.setText("Reparaciones");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnireportes.add(jMenuItem6);

        jMenuItem8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem8.setText("Insumos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnireportes.add(jMenuItem8);

        jMenuItem7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem7.setText("Ventas Diarias");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnireportes.add(jMenuItem7);

        jMenuItem10.setText("Ventas Mensuales");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        mnireportes.add(jMenuItem10);

        jMenuBar1.add(mnireportes);

        mniayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/help.png"))); // NOI18N
        mniayuda.setText("Ayuda");
        mniayuda.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniayuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mniayuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mniayuda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mniayuda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mniacercade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniacercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/information.png"))); // NOI18N
        mniacercade.setText("Acerca de");
        mniacercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniacercadeActionPerformed(evt);
            }
        });
        mniayuda.add(mniacercade);

        jMenuItem9.setText("jMenuItem9");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mniayuda.add(jMenuItem9);

        jMenuBar1.add(mniayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpescritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpescritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnicambiarpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnicambiarpassActionPerformed
        CambioPassword cpass = new CambioPassword(null, true);
        cpass.setVisible(true);
    }//GEN-LAST:event_mnicambiarpassActionPerformed

    private void mniacercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniacercadeActionPerformed
        Acercade acerca = new Acercade(null, true);
        acerca.setVisible(true);
    }//GEN-LAST:event_mniacercadeActionPerformed

    private void mnicerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnicerrarsesionActionPerformed
        int salir = JOptionPane.showConfirmDialog(this, "¿Realmente desea cerrar la sesión actual?", "Cerrando sesión", 0, 3);
        if (salir == JOptionPane.OK_OPTION) {
            //deshabilitar menu, imagen y label de usuario
            mnipersonal.setVisible(false);
            mnireportes.setVisible(false);
            lblimg.setIcon(iconoDesconectado);
            paneldueño.setVisible(false);
            lblusuario.setText("Usuario Desconectado");
            lbltipo.setVisible(false);
            paneldueño.setVisible(false);
            paneljefe.setVisible(false);
            panelmecanico.setVisible(false);
            panelsecretaria.setVisible(false);
            JOptionPane.showMessageDialog(this, "Has cerrado correctamente la sesión");
            //System.exit(0);
            this.dispose();
            Principal x = new Principal();
            x.setVisible(true);
        }
    }//GEN-LAST:event_mnicerrarsesionActionPerformed

    private void mnicerrarsesionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnicerrarsesionItemStateChanged

    }//GEN-LAST:event_mnicerrarsesionItemStateChanged

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void mnirepdesperfectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnirepdesperfectosActionPerformed
        try {
            conexion = claseConectar.ConexionConBaseDatos.getConexion();
            JasperReport reportes = JasperCompileManager.compileReport("reportesdesp.jrxml");
            JasperPrint print = JasperFillManager.fillReport(reportes, null, conexion/*getConexion()*/);
            JasperViewer view = new JasperViewer(print, false);
            JOptionPane.showMessageDialog(null, "Esto puede tardar unos segundos, espere porfavor", "El sistema está generando el reporte", JOptionPane.WARNING_MESSAGE);
            view.setTitle("Reporte de Desperfectos");
            view.setExtendedState(this.MAXIMIZED_BOTH);
            view.setVisible(true);
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
    }//GEN-LAST:event_mnirepdesperfectosActionPerformed

    private void mnirepmarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnirepmarcasActionPerformed
        try {
            conexion = claseConectar.ConexionConBaseDatos.getConexion();
            JasperReport reportes = JasperCompileManager.compileReport("reportemarcas.jrxml");
            JasperPrint print = JasperFillManager.fillReport(reportes, null, conexion/*getConexion()*/);
            JasperViewer view = new JasperViewer(print, false);
            JOptionPane.showMessageDialog(null, "Esto puede tardar unos segundos, espere porfavor", "El sistema está generando el reporte", JOptionPane.WARNING_MESSAGE);
            view.setTitle("Reporte de Marcas");
            view.setExtendedState(this.MAXIMIZED_BOTH);
            view.setVisible(true);
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
    }//GEN-LAST:event_mnirepmarcasActionPerformed

    private void mniusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniusersActionPerformed
        try {
            conexion = claseConectar.ConexionConBaseDatos.getConexion();
            JasperReport reportes = JasperCompileManager.compileReport("reporteusuarios.jrxml");
            JasperPrint print = JasperFillManager.fillReport(reportes, null, conexion/*getConexion()*/);
            JasperViewer view = new JasperViewer(print, false);
            JOptionPane.showMessageDialog(null, "Esto puede tardar unos segundos, espere porfavor", "El sistema está generando el reporte", JOptionPane.WARNING_MESSAGE);
            view.setTitle("Reporte de Usuarios del Sistema");
            view.setExtendedState(this.MAXIMIZED_BOTH);
            view.setVisible(true);
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
    }//GEN-LAST:event_mniusersActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Privilegios del sistema
        if (Login.tipoUsuario == 1) {
            paneldueño.setVisible(true);
            paneljefe.setVisible(false);
            panelmecanico.setVisible(false);
            panelsecretaria.setVisible(false);
            /*btnclientes.setVisible(false);
             btnmarcas.setVisible(false);
             btnvehiculos.setVisible(false);
             btndesperfectos.setVisible(false);
             btndiagnostico.setVisible(false);
             btnreparaciones.setVisible(false);
             btnvtains.setVisible(false);
             //borrar despues
             mnisistema.setVisible(false);
             mniproceso.setVisible(false);
             mniconsultas.setVisible(false);
             mnidiag.setVisible(false);
             mnirep.setVisible(false);*/
        }
        if (Login.tipoUsuario == 2) {
            paneldueño.setVisible(false);
            paneljefe.setVisible(true);
            panelmecanico.setVisible(false);
            panelsecretaria.setVisible(false);
            /*btnbd.setVisible(false);
             mnireportes.setVisible(false);
             btndiagnostico.setVisible(false);
             btnreparaciones.setVisible(false);
             btnvtains.setVisible(false);
             //borrar despues
             mnibd.setVisible(false);
             mniprincipal.setVisible(false);
            
             mnisistema.setVisible(false);
             mniproceso.setVisible(false);
             mniconsultas.setVisible(false);
             mnidiag.setVisible(false);
             mnirep.setVisible(false);*/
        }

        if (Login.tipoUsuario == 3) {
            paneldueño.setVisible(false);
            paneljefe.setVisible(false);
            panelmecanico.setVisible(true);
            panelsecretaria.setVisible(false);
            /*btnclientes.setVisible(false);
             btnmarcas.setVisible(false);
             btnvehiculos.setVisible(false);
             btndesperfectos.setVisible(false);
             btnusuarios.setVisible(false);
             btninsumos.setVisible(false);
             btnbd.setVisible(false);
             btncvi.setVisible(false);
             mnireportes.setVisible(false);
             btnvtains.setVisible(false);
             //borrar despues
             mnisistema.setVisible(false);
             mnidatos.setVisible(false);
             mniproceso.setVisible(false);
             mniconsultas.setVisible(false);
             mnireportes.setVisible(false);
             mnivi.setVisible(false);*/
        }
        if (Login.tipoUsuario == 4) {
            paneldueño.setVisible(false);
            paneljefe.setVisible(false);
            panelmecanico.setVisible(false);
            panelsecretaria.setVisible(true);
            /*btnusuarios.setVisible(false);
             btninsumos.setVisible(false);
             btnbd.setVisible(false);
             btnclientes.setVisible(false);
             btnmarcas.setVisible(false);
             btnvehiculos.setVisible(false);
             btndesperfectos.setVisible(false);
             btndiagnostico.setVisible(false);
             btnreparaciones.setVisible(false);
             btncvi.setVisible(false);
             //no ver menu
            
             mnisistema.setVisible(false);
             mniproceso.setVisible(false);
             mniconsultas.setVisible(false);
             mnidiag.setVisible(false);
             mnirep.setVisible(false);
             mniconsultas.setVisible(false);*/
        }
    }//GEN-LAST:event_formWindowOpened

    private void mnirepclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnirepclientesActionPerformed
        try {
            conexion = claseConectar.ConexionConBaseDatos.getConexion();
            JasperReport reportes = JasperCompileManager.compileReport("reporteclientes.jrxml");
            JasperPrint print = JasperFillManager.fillReport(reportes, null, conexion);
            JasperViewer view = new JasperViewer(print, false);
            JOptionPane.showMessageDialog(null, "Esto puede tardar unos segundos, espere porfavor", "El sistema está generando el reporte", JOptionPane.WARNING_MESSAGE);
            view.setTitle("Reporte de Clientes");
            view.setExtendedState(this.MAXIMIZED_BOTH);
            view.setVisible(true);
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
    }//GEN-LAST:event_mnirepclientesActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            conexion = claseConectar.ConexionConBaseDatos.getConexion();
            JasperReport reportes = JasperCompileManager.compileReport("reporteinsumos.jrxml");
            JasperPrint print = JasperFillManager.fillReport(reportes, null, conexion);
            JasperViewer view = new JasperViewer(print, false);
            JOptionPane.showMessageDialog(null, "Esto puede tardar unos segundos, espere porfavor", "El sistema está generando el reporte", JOptionPane.WARNING_MESSAGE);
            view.setTitle("Reporte de Insumos");
            view.setExtendedState(this.MAXIMIZED_BOTH);
            view.setVisible(true);
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void btnbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbdActionPerformed
        BaseDatos base = new BaseDatos(null, true);
        base.setVisible(true);
    }//GEN-LAST:event_btnbdActionPerformed

    private void btnusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuariosActionPerformed
        if (!us.isVisible()) {
            boolean mostrar = true;
            for (int a = 0; a < jdpescritorio.getComponentCount(); a++) { // verificar si es instancia de algun componente que ya este en el jdesktoppane
                if (us.getClass().isInstance(jdpescritorio.getComponent(a))) {
                    System.out.println("Usuarios: Esto no se volverá a mostrar porque ya está abierta la ventana");
                    mostrar = false;
                } else {
                    System.out.println("Usuarios: No lo es, puede mostrarse");
                }
            }
            if (mostrar) {
                jdpescritorio.add(us);
            }
            us.setVisible(true);
        } else {
            System.out.println("Usuarios: Esto no se volverá a mostrar porque ya está abierta la ventana");
        }
    }//GEN-LAST:event_btnusuariosActionPerformed

    private void btninsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsumosActionPerformed
        if (!in.isVisible()) {
            boolean mostrar = true;
            for (int a = 0; a < jdpescritorio.getComponentCount(); a++) { // verificar si es instancia de algun componente que ya este en el jdesktoppane
                if (in.getClass().isInstance(jdpescritorio.getComponent(a))) {
                    System.out.println("Insumos: Esto no se volverá a mostrar porque ya está abierta la ventana");
                    mostrar = false;
                } else {
                    System.out.println("Insumos: No lo es, puede mostrarse");
                }
            }
            if (mostrar) {
                jdpescritorio.add(in);
            }
            in.show();
        } else {
            System.out.println("Insumos: Esto no se volverá a mostrar porque ya está abierta la ventana");
        }
    }//GEN-LAST:event_btninsumosActionPerformed

    private void btncviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncviActionPerformed
        if (!ccvta.isVisible()) {
            boolean mostrar = true;
            for (int a = 0; a < jdpescritorio.getComponentCount(); a++) { // verificar si es instancia de algun componente que ya este en el jdesktoppane
                if (ccvta.getClass().isInstance(jdpescritorio.getComponent(a))) {
                    System.out.println("Consulta Comprobante: Esto no se volverá a mostrar porque ya está abierta la ventana");
                    mostrar = false;
                } else {
                    System.out.println("Consulta Comprobante: No lo es, puede mostrarse");
                }
            }
            if (mostrar) {
                jdpescritorio.add(ccvta);
            }
            ccvta.show();
        } else {
            System.out.println("Consulta Comprobante: Esto no se volverá a mostrar porque ya está abierta la ventana");
        }
    }//GEN-LAST:event_btncviActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
//        detallediagnostico ccvta = new detallediagnostico(); //crear el nuevo formulario
//        boolean mostrar = true;
//        for (int a = 0; a < jdpescritorio.getComponentCount(); a++) { // verificar si es instancia de algun componente que ya este en el jdesktoppane
//            if (ccvta.getClass().isInstance(jdpescritorio.getComponent(a))) {
//                System.out.println("Consulta Comprobante: Esto no se volverá a mostrar porque ya está abierta la ventana");
//                mostrar = false;
//            } else {
//                System.out.println("Consulta Comprobante: No lo es, puede mostrarse");
//            }
//        }
//        if (mostrar) {
//            jdpescritorio.add(ccvta);
//        }
//        ccvta.show();
        
//        Correito correo = new Correito(null, true);
//        correo.setVisible(true);
       
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void btnvtainsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvtainsActionPerformed
        if (!cvta.isVisible()) {
            boolean mostrar = true;
            for (int a = 0; a < jdpescritorio.getComponentCount(); a++) { // verificar si es instancia de algun componente que ya este en el jdesktoppane
                if (cvta.getClass().isInstance(jdpescritorio.getComponent(a))) {
                    System.out.println("Comprobante: Esto no se volverá a mostrar porque ya está abierta la ventana");
                    mostrar = false;
                } else {
                    System.out.println("Comprobante: No lo es, puede mostrarse");
                    ComprobanteVta.txtvendedor.setText("" + Login.Nombres + " " + Login.Apellidos);
                    ComprobanteVta.txtvendedor.setDisabledTextColor(Color.blue);
                }
            }
            if (mostrar) {
                jdpescritorio.add(cvta);
            }
            cvta.show();
        } else {
            System.out.println("Comprobante: Esto no se volverá a mostrar porque ya está abierta la ventana");
        }
    }//GEN-LAST:event_btnvtainsActionPerformed

    private void btnreparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreparacionesActionPerformed
        reparacion rep = new reparacion(); //crear el nuevo formulario
        boolean mostrar = true;
        for (int a = 0; a < jdpescritorio.getComponentCount(); a++) { // verificar si es instancia de algun componente que ya este en el jdesktoppane
            if (rep.getClass().isInstance(jdpescritorio.getComponent(a))) {
                System.out.println("Reparación Precios Desperfectos: Esto no se volverá a mostrar porque ya está abierta la ventana");
                mostrar = false;
            } else {
                System.out.println("Reparación: No lo es, puede mostrarse");
            }
        }
        if (mostrar) {
            jdpescritorio.add(rep);
        }
        rep.show();

//        jdpescritorio.removeAll();
//        jdpescritorio.updateUI();
//        reparacion ventana = reparacion.getInstancia();
//        jdpescritorio.add(ventana);
//        ventana.show();
    }//GEN-LAST:event_btnreparacionesActionPerformed

    private void btndiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiagnosticoActionPerformed
        if (!diag.isVisible()) {
            boolean mostrar = true;
            for (int a = 0; a < jdpescritorio.getComponentCount(); a++) { // verificar si es instancia de algun componente que ya este en el jdesktoppane
                if (diag.getClass().isInstance(jdpescritorio.getComponent(a))) {
                    System.out.println("Diagnóstico: Esto no se volverá a mostrar porque ya está abierta la ventana");
                    mostrar = false;
                } else {
                    System.out.println("Diagnóstico: No lo es, puede mostrarse");
                    diagnostico.txtmecanico.setText(""+Login.Nombres+" "+Login.Apellidos);
                    diagnostico.txtmecanico.setDisabledTextColor(Color.blue);
                }
            }
            if (mostrar) {
                jdpescritorio.add(diag);
            }
            diag.show();
        } else {
            System.out.println("Diagnóstico: Esto no se volverá a mostrar porque ya está abierta la ventana");
        }
    }//GEN-LAST:event_btndiagnosticoActionPerformed

    private void btndesperfectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndesperfectosActionPerformed
        if (!d.isVisible()) {
            boolean mostrar = true;
            for (int a = 0; a < jdpescritorio.getComponentCount(); a++) { // verificar si es instancia de algun componente que ya este en el jdesktoppane
                if (d.getClass().isInstance(jdpescritorio.getComponent(a))) {
                    System.out.println("Desperfectos: Esto no se volverá a mostrar porque ya está abierta la ventana");
                    mostrar = false;
                } else {
                    System.out.println("Desperfectos: No lo es, puede mostrarse");
                }
            }
            if (mostrar) {
                jdpescritorio.add(d);
            }
            d.show();
        } else {
            System.out.println("Desperfectos: Esto no se volverá a mostrar porque ya está abierta la ventana");
        }
    }//GEN-LAST:event_btndesperfectosActionPerformed

    private void btnvehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvehiculosActionPerformed
        if (!v.isVisible()) {
            boolean mostrar = true;
            for (int a = 0; a < jdpescritorio.getComponentCount(); a++) { // verificar si es instancia de algun componente que ya este en el jdesktoppane
                if (v.getClass().isInstance(jdpescritorio.getComponent(a))) {
                    System.out.println("Vehículos: Esto no se volverá a mostrar porque ya está abierta la ventana");
                    mostrar = false;
                } else {
                    System.out.println("Vehículos: No lo es, puede mostrarse");
                }
            }
            if (mostrar) {
                jdpescritorio.add(v);
            }
            v.show();
        } else {
            System.out.println("Vehículos: Esto no se volverá a mostrar porque ya está abierta la ventana");
        }
    }//GEN-LAST:event_btnvehiculosActionPerformed

    private void btnmarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarcasActionPerformed
        if (!mv.isVisible()) {
            boolean mostrar = true;
            for (int a = 0; a < jdpescritorio.getComponentCount(); a++) { // verificar si es instancia de algun componente que ya este en el jdesktoppane
                if (mv.getClass().isInstance(jdpescritorio.getComponent(a))) {
                    System.out.println("Marcas: Esto no se volverá a mostrar porque ya está abierta la ventana");
                    mostrar = false;
                } else {
                    System.out.println("Marcas: No lo es, puede mostrarse");
                }
            }
            if (mostrar) {
                jdpescritorio.add(mv);
            }
            mv.show();
        } else {
            System.out.println("Marcas: Esto no se volverá a mostrar porque ya está abierta la ventana");
        }
    }//GEN-LAST:event_btnmarcasActionPerformed

    private void btnclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientesActionPerformed
        if (!cs.isVisible()) {
            boolean mostrar = true;
            for (int a = 0; a < jdpescritorio.getComponentCount(); a++) { // verificar si es instancia de algun componente que ya este en el jdesktoppane
                if (cs.getClass().isInstance(jdpescritorio.getComponent(a))) {
                    System.out.println("Clientes: Esto no se volverá a mostrar porque ya está abierta la ventana");
                    mostrar = false;
                } else {
                    System.out.println("Clientes: No lo es, puede mostrarse");
                }
            }
            if (mostrar) {
                jdpescritorio.add(cs);
            }
            cs.show();
        } else {
            System.out.println("Clientes: Esto no se volverá a mostrar porque ya está abierta la ventana");
        }
    }//GEN-LAST:event_btnclientesActionPerformed

    private void btnusuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuarios1ActionPerformed
        if (!us2.isVisible()) {
            boolean mostrar = true;
            for (int a = 0; a < jdpescritorio.getComponentCount(); a++) { // verificar si es instancia de algun componente que ya este en el jdesktoppane
                if (us2.getClass().isInstance(jdpescritorio.getComponent(a))) {
                    System.out.println("Usuarios: Esto no se volverá a mostrar porque ya está abierta la ventana");
                    mostrar = false;
                } else {
                    System.out.println("Usuarios: No lo es, puede mostrarse");
                }
            }
            if (mostrar) {
                jdpescritorio.add(us2);
            }
            us2.show();
        } else {
            System.out.println("Usuarios: Esto no se volverá a mostrar porque ya está abierta la ventana");
        }
    }//GEN-LAST:event_btnusuarios1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       try {
            conexion = claseConectar.ConexionConBaseDatos.getConexion();
            Map parametro = new HashMap();
            JasperReport reportes = JasperCompileManager.compileReport("reportevtasdiarias.jrxml");
            parametro.put("Fecha", lbfecha.getText());
            //se carga el reporte
            //se procesa el archivo jasper
            JasperPrint print = JasperFillManager.fillReport(reportes, parametro, conexion);
            JOptionPane.showMessageDialog(null, "Esto puede tardar unos segundos, espere porfavor", "El sistema está generando el comprobante de venta", JOptionPane.WARNING_MESSAGE);
            JasperViewer.viewReport(print, false);
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        bxfecha bxf = new bxfecha(null, true);
        bxf.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AceptacionReparaciones Arep = new AceptacionReparaciones(); //crear el nuevo formulario
        boolean mostrar = true;
        for (int a = 0; a < jdpescritorio.getComponentCount(); a++) { // verificar si es instancia de algun componente que ya este en el jdesktoppane
            if (Arep.getClass().isInstance(jdpescritorio.getComponent(a))) {
                System.out.println("Reparación Precios Desperfectos: Esto no se volverá a mostrar porque ya está abierta la ventana");
                mostrar = false;
            } else {
                System.out.println("Reparación: No lo es, puede mostrarse");
            }
        }
        if (mostrar) {
            jdpescritorio.add(Arep);
        }
        Arep.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*new Principal().setVisible(true);*/
                new Thread(new start()).start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbd;
    private javax.swing.JButton btnclientes;
    private javax.swing.JButton btncvi;
    private javax.swing.JButton btndesperfectos;
    private javax.swing.JButton btndiagnostico;
    private javax.swing.JButton btninsumos;
    private javax.swing.JButton btnmarcas;
    private javax.swing.JButton btnreparaciones;
    private javax.swing.JButton btnusuarios;
    private javax.swing.JButton btnusuarios1;
    private javax.swing.JButton btnvehiculos;
    private javax.swing.JButton btnvtains;
    private elaprendiz.gui.varios.ClockDigital clockDigital1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public static javax.swing.JDesktopPane jdpescritorio;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblhora;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JMenuItem mniacercade;
    private javax.swing.JMenu mniayuda;
    private javax.swing.JMenuItem mnicambiarpass;
    private javax.swing.JMenuItem mnicerrarsesion;
    private javax.swing.JMenu mnipersonal;
    private javax.swing.JMenuItem mnirepclientes;
    private javax.swing.JMenuItem mnirepdesperfectos;
    private javax.swing.JMenuItem mnirepmarcas;
    private javax.swing.JMenu mnireportes;
    private javax.swing.JMenuItem mniusers;
    private elaprendiz.gui.panel.PanelCurves panelCurves1;
    private elaprendiz.gui.panel.PanelImage panelImagen;
    private elaprendiz.gui.panel.PanelTranslucido paneldueño;
    private elaprendiz.gui.panel.PanelTranslucido paneljefe;
    private elaprendiz.gui.panel.PanelTranslucido panelmecanico;
    private elaprendiz.gui.panel.PanelTranslucido panelsecretaria;
    // End of variables declaration//GEN-END:variables
}
