/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgtmtr;

import CapaDatos.Class_Conectar;
import java.awt.BorderLayout;
import java.awt.Container;
import java.sql.Connection;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author ZuluCorp
 */
public class repdesp extends javax.swing.JInternalFrame {

    /**
     * Creates new form repdesp
     */
    public repdesp() {
        initComponents();
    }

      public repdesp(String fileName){
        this(fileName,null);
    }
    public repdesp(String fileName,HashMap parametro){
        this();
        Class_Conectar conectar=new Class_Conectar();
        try{
            Connection cn=conectar.conectar();
            JasperPrint print=JasperFillManager.fillReport(fileName,parametro,cn);
            JRViewer viwer=new  JRViewer(print);
            Container c=getContentPane();
            c.setLayout(new BorderLayout());
            c.add(viwer);
             }catch(Exception e){
                    }
           }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
