/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgtmtr;

import static claseConectar.ConexionConBaseDatos.conexion;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import static sgtmtr.ComprobanteVta.tbvprod;

/**
 *
 * @author ZuluCorp
 */
public class SeleccionDesperfecto extends javax.swing.JDialog {
    CalculaPrecioTB calcula = new CalculaPrecioTB();
    /**
     * Creates new form SeleccionProducto
     */
    public SeleccionDesperfecto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Seleccione el o los desperfectos");
        mostrardatos("");
        anchocolumnas();    
    }
    void mostrardatos(String valor) {
        /*String id=txtidmarca.getText();
        String NM=txtmn.getText();*/
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        tbdesp.setModel(modelo);
        String sql = "";
        if (valor.equals("")) {
            sql = "SELECT * FROM desperfectos";
        } else {
            //sql = "SELECT * FROM insumos WHERE Codigo='" + id + "'";
        }

        String[] datos = new String[3];
        try {
            conexion = claseConectar.ConexionConBaseDatos.getConexion();
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                modelo.addRow(datos);
            }
            tbdesp.setModel(modelo);
           //tbmarcas.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error " + e.getMessage().toString());
        } finally {
            claseConectar.ConexionConBaseDatos.metodoCerrarConexiones(conexion);
        }
    }
    
    void anchocolumnas() {
        tbdesp.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        tbdesp.getColumnModel().getColumn(0).setWidth(100);
        tbdesp.getColumnModel().getColumn(0).setMaxWidth(100);
        tbdesp.getColumnModel().getColumn(0).setMinWidth(100);
        
        tbdesp.getColumnModel().getColumn(1).setWidth(200);
        tbdesp.getColumnModel().getColumn(1).setMaxWidth(200);
        tbdesp.getColumnModel().getColumn(1).setMinWidth(200);
        
        tbdesp.getColumnModel().getColumn(0).setWidth(100);
        tbdesp.getColumnModel().getColumn(0).setMaxWidth(100);
        tbdesp.getColumnModel().getColumn(0).setMinWidth(100);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jsp = new javax.swing.JScrollPane();
        tbdesp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione los desperfectos del vehículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        tbdesp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        //Deshabilitar edicion de tabla
        tbdesp = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        //cambiar color de fila
        tbdesp.setSelectionBackground(Color.LIGHT_GRAY);
        tbdesp.setSelectionForeground(Color.blue);
        tbdesp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbdesp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbdesp.getTableHeader().setResizingAllowed(false);
        tbdesp.getTableHeader().setReorderingAllowed(false);
        tbdesp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbdespMousePressed(evt);
            }
        });
        jsp.setViewportView(tbdesp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tbdespMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdespMousePressed
        SpinnerNumberModel numerito = new SpinnerNumberModel(1, 0, 10, 1);
        JSpinner spinner = new JSpinner(numerito);
        int option = JOptionPane.showOptionDialog(null, spinner, "Seleccione o Ingrese Cantidad", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (option == JOptionPane.CANCEL_OPTION) {
    // user hit cancel
        } else if (option == JOptionPane.OK_OPTION) {
            try {
            DefaultTableModel tabladet = (DefaultTableModel) diagnostico.tbdiag.getModel();
            String[] dato = new String[5];
            int fila = SeleccionDesperfecto.tbdesp.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ningún registro");
            } else {
                String cod = SeleccionDesperfecto.tbdesp.getValueAt(fila, 0).toString();
                String desc = SeleccionDesperfecto.tbdesp.getValueAt(fila, 1).toString();
                String preunit = SeleccionDesperfecto.tbdesp.getValueAt(fila, 2).toString();
                int c = 0;
                int j = 0;
                //SpinnerNumberModel sModel = new SpinnerNumberModel(0, 0, 30, 1);
                //JSpinner spinner = new JSpinner(sModel);
                String cant = numerito.getValue().toString();
                //validar que no sea menor que 0 o sea -1 etc menos letras... o cambiar tema aca
                if ((cant.equals("0"))) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar un valor mayor que 0");
                } else {
                    int canting = Integer.parseInt(cant);
                        if (canting > 0) {
                            for (int i = 0; i < diagnostico.tbdiag.getRowCount(); i++) {
                                Object com = diagnostico.tbdiag.getValueAt(i, 0);
                                if (cod.equals(com)) {
                                    j = i;
                                    diagnostico.tbdiag.setValueAt(canting, i, 2);
                                    c = c + 1;
                                    calcula.calcularRep();
                                }
                                this.dispose();
                            }
                        }
                        if (c == 0) {
                            dato[0] = cod;
                            dato[1] = desc;
                            dato[2] = cant;
                            dato[3] = preunit;
//                            dato[4] = presubtotal;
//                            dato[5] = Estado;
                            tabladet.addRow(dato);
                            diagnostico.tbdiag.setModel(tabladet);
                            calcula.calcularRep();
                            this.dispose();
                        }
                }
            }
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_tbdespMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionDesperfecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionDesperfecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionDesperfecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionDesperfecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionDesperfecto dialog = new SeleccionDesperfecto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jsp;
    public static javax.swing.JTable tbdesp;
    // End of variables declaration//GEN-END:variables
}
