/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgtmtr;

import claseConectar.conectar;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static sgtmtr.ComprobanteVta.tbvprod;

/**
 *
 * @author ZuluCorp
 */
public class SeleccionProducto extends javax.swing.JDialog {
    CalculaPrecioTB calcula = new CalculaPrecioTB();
    /**
     * Creates new form SeleccionProducto
     */
    public SeleccionProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Seleccione el Insumo");
        mostrardatos("");
        anchocolumnas();
    }
    void mostrardatos(String valor) {
        /*String id=txtidmarca.getText();
        String NM=txtmn.getText();*/
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        tbprod.setModel(modelo);
        String sql = "";
        if (valor.equals("")) {
            sql = "SELECT * FROM insumos";
        } else {
            //sql = "SELECT * FROM insumos WHERE Codigo='" + id + "'";
        }

        String[] datos = new String[4];
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/techorojo", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                modelo.addRow(datos);
            }
            tbprod.setModel(modelo);
           //tbmarcas.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error " + e.getMessage().toString());
        }
    }
    
    void anchocolumnas() {
        tbprod.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        tbprod.getColumnModel().getColumn(0).setWidth(100);
        tbprod.getColumnModel().getColumn(0).setMaxWidth(100);
        tbprod.getColumnModel().getColumn(0).setMinWidth(100);
        
        tbprod.getColumnModel().getColumn(1).setWidth(200);
        tbprod.getColumnModel().getColumn(1).setMaxWidth(200);
        tbprod.getColumnModel().getColumn(1).setMinWidth(200);
        
        tbprod.getColumnModel().getColumn(0).setWidth(100);
        tbprod.getColumnModel().getColumn(0).setMaxWidth(100);
        tbprod.getColumnModel().getColumn(0).setMinWidth(100);
        
        tbprod.getColumnModel().getColumn(1).setWidth(100);
        tbprod.getColumnModel().getColumn(1).setMaxWidth(100);
        tbprod.getColumnModel().getColumn(1).setMinWidth(100);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jsp = new javax.swing.JScrollPane();
        tbprod = new javax.swing.JTable();
        btnenviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbprod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        //Deshabilitar edicion de tabla
        tbprod = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        //cambiar color de fila
        tbprod.setSelectionBackground(Color.LIGHT_GRAY);
        tbprod.setSelectionForeground(Color.blue);
        tbprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsp.setViewportView(tbprod);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnenviar.setText("Agregar");
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btnenviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnenviar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String comparar(String cod) {
        String cant = "";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM insumos WHERE Codigo='" + cod + "'");
            while (rs.next()) {
                cant = rs.getString(4);
            }

        } catch (SQLException ex) {
            Logger.getLogger(SeleccionProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        return cant;

    }
    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        try {
            DefaultTableModel tabladet = (DefaultTableModel) ComprobanteVta.tbvprod.getModel();
            String[] dato = new String[5];
            int fila = tbprod.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "No  ha seleccionado ningun registro");
            } else {
                String cod = tbprod.getValueAt(fila, 0).toString();
                String desc = tbprod.getValueAt(fila, 1).toString();
                String preunit = tbprod.getValueAt(fila, 2).toString();
                int c = 0;
                int j = 0;
                String cant = JOptionPane.showInputDialog("Ingrese Cantidad a Vender");
                //validar que no sea menor que 0 o sea -1 etc menos letras... o cambiar tema aca
                if ((cant.equals("")) || (cant.equals("0"))) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar algun valor mayor que 0");
                } else {
                    int canting = Integer.parseInt(cant);
                    int comp = Integer.parseInt(comparar(cod));
                    if (canting > comp) {
                        JOptionPane.showMessageDialog(this, "Ud. no cuenta con el stock apropiado");
                    } else {
                        for (int i = 0; i < ComprobanteVta.tbvprod.getRowCount(); i++) {
                            Object com = ComprobanteVta.tbvprod.getValueAt(i, 0);
                            if (cod.equals(com)) {
                                j = i;
                                ComprobanteVta.tbvprod.setValueAt(cant, i, 3);
                                c = c + 1;
                            }
                        }
                        if (c == 0) {
                            dato[0] = cod;
                            dato[1] = desc;
                            dato[2] = cant;
                            dato[3] = preunit;
                            tabladet.addRow(dato);
                            ComprobanteVta.tbvprod.setModel(tabladet);
                            calcula.calcular();
                            this.dispose();
                        }
                    }
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnenviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionProducto dialog = new SeleccionProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenviar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTable tbprod;
    // End of variables declaration//GEN-END:variables
    conectar cc= new conectar();
    Connection cn = cc.conexion();
}
