/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgtmtr;


import static claseConectar.ConexionConBaseDatos.conexion;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZuluCorp
 */
public class SeleccionaCantidad extends javax.swing.JDialog {
    CalculaPrecioTB calcula = new CalculaPrecioTB();
    ValidarCaracteres validaDato = new ValidarCaracteres();
    /**
     * Creates new form SeleccionaCantidad
     */
    public SeleccionaCantidad(java.awt.Frame parent, boolean modal) {
        super(parent,"Selección de Cantidad", modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    String comparar(String cod) {
        String option = "";
        try {
            conexion = claseConectar.ConexionConBaseDatos.getConexion();
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM insumos WHERE Codigo='" + cod + "'");
            while (rs.next()) {
                option = rs.getString(4);
            }

        } catch (SQLException ex) {
            Logger.getLogger(SeleccionProducto.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            claseConectar.ConexionConBaseDatos.metodoCerrarConexiones(conexion);
        }
        return option;

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numerito = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        numerito.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numerito.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        numerito.setToolTipText("");
        numerito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeritoKeyTyped(evt);
            }
        });

        jLabel1.setText("Seleccione cantidad");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(numerito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numerito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DefaultTableModel tabladet = (DefaultTableModel) ComprobanteVta.tbvprod.getModel();
            String[] dato = new String[5];
            int fila = SeleccionProducto.tbprod.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ningun registro");
            } else {
                String cod = SeleccionProducto.tbprod.getValueAt(fila, 0).toString();
                String desc = SeleccionProducto.tbprod.getValueAt(fila, 1).toString();
                String preunit = SeleccionProducto.tbprod.getValueAt(fila, 2).toString();
                int c = 0;
                int j = 0;
                //SpinnerNumberModel sModel = new SpinnerNumberModel(0, 0, 30, 1);
                //JSpinner spinner = new JSpinner(sModel);
                String cant = numerito.getValue().toString();
                //validar que no sea menor que 0 o sea -1 etc menos letras... o cambiar tema aca
                if ((cant.equals("0"))) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar algun valor mayor que 0");
                } else {
                    int canting = Integer.parseInt(cant);
                    int comp = Integer.parseInt(comparar(cod));
                    if (canting > comp) {
                        JOptionPane.showMessageDialog(this, "Ud. no cuenta con el stock apropiado");
                    } else {
                        if (canting > 0) {
                            for (int i = 0; i < ComprobanteVta.tbvprod.getRowCount(); i++) {
                                Object com = ComprobanteVta.tbvprod.getValueAt(i, 0);
                                if (cod.equals(com)) {
                                    j = i;
                                    ComprobanteVta.tbvprod.setValueAt(canting, i, 2);
                                    c = c + 1;
                                    calcula.calcular();
                                }
                                this.dispose();
                            }
                        } else {
                            /*JOptionPane.showMessageDialog(this, "Debe ingresar algun valor mayor que 0");
                            DefaultTableModel model = (DefaultTableModel) ComprobanteVta.tbvprod.getModel();
                            //int fila = ComprobanteVta.tbvprod.getSelectedRow();
                            if (fila < 0) {
                                model.removeRow(fila);
                                calcula.calcular();
                                ComprobanteVta.txtmtotal.setText("");
                                model.removeRow(fila);
                                calcula.calcular();
                            }*/
                        }
                        if (c == 0) {
                            dato[0] = cod;
                            dato[1] = desc;
                            dato[2] = cant;
                            dato[3] = preunit;
                            tabladet.addRow(dato);
                            ComprobanteVta.tbvprod.setModel(tabladet);
                            calcula.calcular();
                            this.dispose();
                        }
                    }
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void numeritoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeritoKeyTyped
        validaDato.soloNumeros(evt);
        //limite de caracteres
        if (numerito.getValue().toString().length() == 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_numeritoKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionaCantidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionaCantidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionaCantidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionaCantidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionaCantidad dialog = new SeleccionaCantidad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner numerito;
    // End of variables declaration//GEN-END:variables
}
